### ISSUE TITLE
[TuyaIR] Failed to change device status due to error system error,please contact the admin

### ISSUE THREAD

**Issue by MadhunterNL** [prasad-edlabadka/homebridge-tuya-ir#50]
I connected a S11 Tuya IR/RF remote (https://nl.aliexpress.com/item/1005003554783995.html?gatewayAdapt=glo2nld) with your plugin in.

It finds the accessoire, but then given an error when using the switch. Is it because this device isn't supported yet or am I doing something wrong?

Its a switch for a roller shutter.

Hope to hear from you as a RF controller isn't supported yet by homekit, this would be most welcome.

**Comment by prasad-edlabadka** [comment]
RF is not supported. Can you please paste logs from homebridge and your config? Roller shutter is not supported but On-Off may work.

**Comment by rafaelfaria** [comment]
I am trying to use this as well with a roller blinder. On/off should be fine to me as I just want to automate to close it at some time of the day through homekit.

however, i am getting:

[15/11/2024, 7:39:28 am] [TuyaIR] Failed to change Bedroom status due to error system error,please contact the admin
[15/11/2024, 7:39:28 am] [TuyaIR] Failed to change Bedroom status due to error system error,please contact the admin

```
{
    "name": "TuyaIR",
    "tuyaAPIClientId": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "tuyaAPISecret": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "deviceRegion": "eu",
    "smartIR": [
        {
            "deviceId": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "autoFetchRemotesFromServer": false,
            "configuredRemotes": [
                {
                    "id": "xxxxxxxxxxxxxxxxxxxxxxxx",
                    "model": "Unknown",
                    "brand": "Unknown"
                }
            ]
        }
    ],
    "platform": "TuyaIR"
}
```

Am i doing something wrong?
